#!/usr/bin/env python3
import sys
import re

from find_booktacular import booktacular  # noqa: F401
# ^ works for submodules since changes path

from booktacular.morescribus.compare import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
